---
galaxy_info:
  author: "Dein Name"
  description: "Ansible Rolle zur Verwaltung von Netbird inklusive GUI"
  company: "Privat"
  license: "MIT"
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - "24.04"
dependencies: []
