---
netbird_state: "installed" # "installed" oder "absent"
netbird_service_state: "started" # "started" oder "stopped"
netbird_service_enabled: false # Nicht beim Systemstart starten, aber standardmäßig laufen
netbird_install_gui: true # Steuert, ob das GUI mitinstalliert werden soll
